[local]
localhost ansible_connection=local

[signlearn]
localhost ansible_connection=local

[signlearn:vars]
ansible_python_interpreter=/usr/bin/python3
app_dir=/var/jenkins_home/workspace/signlearn-pipeline
frontend_port=3000
backend_port=8000